# format after processing:
# each level is a dictionary:
# geometry: list of strings, each string is a line, each character a field:
#   space: no field
#   X : blank field
#   G : end field
#   s : round switch, can be hit by any part of the block
#   h : x switch, can be switched only if the block hits the switch vertically
#   l, r : if a switch is hit, these fields appear or disappear
#   k, q : same as l and r, but initially on instead of off
#   f : can be visited only in split mode, or not standing
# start: x, y start coordinate of the block

levels = [
    # {  
    #      'geometry': [  'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXXXXXX',
    #                     'XXXXXGXXXX'],
    #     'start': {'x': 0, 'y': 0},
    #     'swatches': []},
    
       {   'geometry': [   '          ',
                        '          ',
                        '     XXX  ',
                        '    XXXX  ',
                        '    XXXX  ',
                        '    XXX   ',
                        '    XXX   ',
                        '   XXXX   ',
                        '  XXXX    ',
                        '  XGXX    ',
                        '  XXXX    ',
                        '   XX     ',
                        '          ',
                        '          ',
                        '          '],
        'start': {'x': 6, 'y': 3},
        'swatches': []},
       
       {   'geometry': ['   XXXXX  ',
                        '   XXXXX  ',
                        '   XXXsX  ',
                        '   XXXXX  ',
                        '    l     ',
                        '    r     ',
                        '   XXXXXX ',
                        '   XXXXXX ',
                        '   XXXXhX ',
                        '   XXXXXX ',
                        '    l     ',
                        '    r     ',
                        '    XXXXX ',
                        '    XXXGX ',
                        '    XXXXX '],
        'start': {'x': 4, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 10}},
                                          {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 11}}],
                            'position': {'x': 7, 'y': 8},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 4}},
                                          {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 5}}],
                            'position': {'x': 6, 'y': 2},
                            'type': 's'}]},
       
       {   'geometry': ['   XXXX   ',
                        '   XXXX   ',
                        '   XXXX   ',
                        '   XXXX   ',
                        '     X    ',
                        '     X    ',
                        '     XXX  ',
                        '     XXX  ',
                        '     XXX  ',
                        '       X  ',
                        '       X  ',
                        '   XXXXX  ',
                        '  XXXXXX  ',
                        '  XXGX    ',
                        '  XXXX    '],
        'start': {'x': 4, 'y': 1},
        'swatches': []},
       
       {   'geometry': ['  XXXXX   ',
                        '  XXXXX   ',
                        '  XXXXX   ',
                        '      Xff ',
                        '       ff ',
                        'XXXX   ff ',
                        'XGXX   ff ',
                        'XXXX   ff ',
                        '  XX   ff ',
                        '  ff  Xff ',
                        'ffffXXX   ',
                        'ffffXXX   ',
                        'fXff      ',
                        'ffff      ',
                        '          '],
        'start': {'x': 3, 'y': 1},
        'swatches': []},
       
       {   'geometry': ['XXX       ',
                        'XGX  XXXX ',
                        'XXX  XXXX ',
                        'XX  XXsXX ',
                        ' X  XXXXX ',
                        ' k  X   k ',
                        ' q  s   q ',
                        ' X  X   X ',
                        ' X  k   s ',
                        ' X  q   X ',
                        ' XXXX   X ',
                        ' XXXX   XX',
                        ' XXXX  XXX',
                        '  XX   XXX',
                        '  Xs   XXX'],
        'start': {'x': 8, 'y': 13},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 6}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 5}}],
                            'position': {'x': 8, 'y': 8},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 1, 'y': 5}},
                                          {   'action': 'on',
                                              'position': {'x': 1, 'y': 6}}],
                            'position': {'x': 6, 'y': 3},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 1, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 1, 'y': 6}}],
                            'position': {'x': 4, 'y': 6},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 1, 'y': 5}},
                                          {   'action': 'onoff',
                                              'position': {'x': 1, 'y': 6}}],
                            'position': {'x': 3, 'y': 14},
                            'type': 's'}]}
        ]